#!/bin/sh

wallpaper=$1

[ -n "$wallpaper" ] || exit 1
[ -f "$wallpaper" ] || exit 1

awww img --resize crop "$wallpaper" \
	--transition-type simple

wal -n -i "$wallpaper"

somebar -c reload-colors
